/* tslint:disable */
/**
 * This file was automatically generated by pulumi-provider-scripts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source Pulumi Schema file,
 * and run "pulumi-provider-scripts gen-provider-types" to regenerate this file. */
import * as pulumi from "@pulumi/pulumi";
export type ConstructComponent<T extends pulumi.ComponentResource = pulumi.ComponentResource> = (name: string, inputs: any, options: pulumi.ComponentResourceOptions) => T;
export type ResourceConstructor = {};
export type Functions = {};
import * as aws from "@pulumi/aws";
import * as cloudflare from "@pulumi/cloudflare";
import * as digitalocean from "@pulumi/digitalocean";
export type targetInputs = "aws" | "cloudflare" | "digitalocean";
export type targetOutputs = "aws" | "cloudflare" | "digitalocean";
