version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/provider"
    schedule:
      interval: "weekly"
      time: "00:01"
      day: "monday"
    commit-message:
      prefix: "[gomod] "
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/sdk"
    schedule:
      interval: "weekly"
      time: "00:01"
      day: "monday"
    commit-message:
      prefix: "[gomod] "
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/provider/cmd/pulumi-resource-clouddns"
    schedule: 
      interval: "daily"
      time: "00:01"
    commit-message:
      prefix: "[npm] "
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: "daily"
      time: "00:01"
    commit-message:
      prefix: "[gha] "
      include: "scope"
