// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace PiersKarsenbarg.Clouddns
{
    [EnumType]
    public readonly struct Target : IEquatable<Target>
    {
        private readonly string _value;

        private Target(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// AWS Route53
        /// </summary>
        public static Target Aws { get; } = new Target("aws");
        /// <summary>
        /// CloudFlare DNS
        /// </summary>
        public static Target Cloudflare { get; } = new Target("cloudflare");
        /// <summary>
        /// Digital Ocean DNS
        /// </summary>
        public static Target Digitalocean { get; } = new Target("digitalocean");

        public static bool operator ==(Target left, Target right) => left.Equals(right);
        public static bool operator !=(Target left, Target right) => !left.Equals(right);

        public static explicit operator string(Target value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is Target other && Equals(other);
        public bool Equals(Target other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
