# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'Target',
]


class Target(str, Enum):
    AWS = "aws"
    """
    AWS Route53
    """
    CLOUDFLARE = "cloudflare"
    """
    CloudFlare DNS
    """
    DIGITALOCEAN = "digitalocean"
    """
    Digital Ocean DNS
    """
