// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const Target = {
    /**
     * AWS Route53
     */
    Aws: "aws",
    /**
     * CloudFlare DNS
     */
    Cloudflare: "cloudflare",
    /**
     * Digital Ocean DNS
     */
    Digitalocean: "digitalocean",
} as const;

export type Target = (typeof Target)[keyof typeof Target];
