// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package clouddns

type Target string

const (
	// AWS Route53
	TargetAws = Target("aws")
	// CloudFlare DNS
	TargetCloudflare = Target("cloudflare")
	// Digital Ocean DNS
	TargetDigitalocean = Target("digitalocean")
)

func init() {
}
