env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  comment-on-pr:
    if: github.event.pull_request.head.repo.full_name != github.repository
    name: comment-on-pr
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2.4.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          PR is now waiting for a maintainer to run the acceptance tests.
    strategy: {}
name: pull-request
"on":
  pull_request_target: {}